services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8090:8090
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: